### ISSUE TITLE
setting the admin email on the login page ?

### ISSUE THREAD

**Issue by kforner** [dennyverbeeck/transmart-docker#3]
Do you know by any chance how to set this email ? 
I tried the obvious variables from your Config.groovy, with no luck...

**Comment by dennyverbeeck** [comment]
I checked the source, the page checks for `com.recomdata.administrator`, not sure how why and when this got out of sync with the variable in `Config.groovy`. Thanks for bringing this up, in the next release we'll use the `com.recomdata.adminEmail`, for now you should be able to use `com.recomdata.administrator`.

**Comment by dennyverbeeck** [comment]
Opend [this pull request](https://github.com/transmart/transmartApp/pull/221) to fix it. Just confirmed `com.recomdata.administrator` sets the admin email on the login page, so closing this issue.

**Comment by kforner** [comment]
Ah sorry I forgot to confirm it worked. thanks again.

**Comment by dennyverbeeck** [comment]
No problem :) glad to help!
